### ISSUE TITLE
Current day not displaying correctly.

### ISSUE THREAD

**Issue by FourStringFunk** [FourStringFunk/cHarris_WorkDay_Planner#4]
Could you figure out why the current day isn't showing correctly on the page?

**Comment by FourStringFunk** [comment]
Uncaught ReferenceError: require is not defined
    at HTMLDocument.<anonymous> (script.js:3:17)
    at j (jquery.min.js:2:29999)
    at k (jquery.min.js:2:30313)

This would suggest the it has something to do with the local nodejs instance. Need to relook at the documentation for dayjs

**Comment by FourStringFunk** [comment]
FIxed it by removing Removed const dayjs = require('dayjs')
